## 01. Initial Data Profiling

--- 

### Objective: 
    
- The objective of this notebook is to perform a thorough initial exploration and profiling of all raw datasets. 

- This step helps us understand the structure, quality, and basic characteristics of the data before    moving to data cleaning, feature engineering, and analysis.

### Why Data Profiling is Needed?

Before cleaning or analyzing any data, it is essential to understand what the data looks like. Data Profiling helps us answer important questions such as:

- How many rows and columns does each table have?
- What are the data types of each column?
- Are there any missing values? If yes, how many and in which columns?
- Are there any duplicate records?
- Which columns can be used as Primary Keys?
- What is the date range of the transactions?

#### 1. Importing libraries

In [1]:
## 1. Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from IPython.display import display

#### 2. Load all Datasets & Set Display

In [2]:
## 2. Set  Display options

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',100)
pd.set_option('display.float_format','{:.2f}'.format)

## 3. Define path

raw_path="C:/Users/Rohit/Project Related to Data Analyst/Indian-E-commerce-Sales-and-Customer-Analytics/data/raw_data/"

# Create a list files we use 

files = {
    "customers" : 'customers.csv',
    "customer_reviews":'customer_reviews.csv',
    "orders":'orders.csv',
    "order_items":'order_items.csv',
    "products":'products.csv',
    "payments":'payments.csv',
    "returns":'returns.csv',
    "shipments":'shipments.csv'
}

## 4. Load all datasets

datasets = {}

for name,filename in files.items():
    file_path = os.path.join(raw_path,filename) 
    
    try:
        datasets[name] = pd.read_csv(file_path)
        print(f"Loaded: {name:15} - {datasets[name].shape[0]:,} rows * {datasets[name].shape[1]} columns")
        print(f"{name} datasets loaded successfully !\n") 
        
    except Exception as e:
        print(f"Failed to Load {filename}: {e}")

Loaded: customers       - 25,000 rows * 17 columns
customers datasets loaded successfully !

Loaded: customer_reviews - 77,530 rows * 8 columns
customer_reviews datasets loaded successfully !

Loaded: orders          - 100,000 rows * 14 columns
orders datasets loaded successfully !

Loaded: order_items     - 254,331 rows * 9 columns
order_items datasets loaded successfully !

Loaded: products        - 550 rows * 14 columns
products datasets loaded successfully !

Loaded: payments        - 100,000 rows * 8 columns
payments datasets loaded successfully !

Loaded: returns         - 12,075 rows * 8 columns
returns datasets loaded successfully !

Loaded: shipments       - 89,681 rows * 11 columns
shipments datasets loaded successfully !

#### 3. Profiling Functions 

- Instead of writing same profiling code to eight dataframe sperately then it's Time consuming that why we process them using loop

In [9]:
# Basic Profiling Function

def profiling_dataframe(name,df):
    print("="*80)
    print(f"Dataset:{name.upper()}")
    print("="*80)
    
    ## Basic Info of rows and columns 
    
    print(f"Shape: {df.shape[0]} rows * {df.shape[1]} columns\n")           ## Gives Total Rows and columns of each datasets.
    
    ## Display data types of Each Datasets
    
    print("Column Name and Data Types:")
    dtype_df = pd.DataFrame({
        "Column" : df.columns,
        "Data types" : df.dtypes.values,
        "Non-Null Count": df.count().values,
        "Null Count": df.isnull().sum().values,
        "Null %" : (df.isnull().sum().values / len(df) * 100).round(2)
    })
    display(dtype_df)
    
   ## Missing Values Summary
     
    print("Missing value:")
    missing = df.isnull().sum()                                             ## Count total Missing value of Each datasets.
    missing = missing[missing >0]
    if len(missing) > 0:
        print("Columns with Missing Values:")
        missing_df = pd.DataFrame({
        'Missing count': missing,
        'Missing %': (missing / len(df) * 100).round(2)
        }).sort_values("Missing %", ascending = False)
        display(missing_df)
    else:
        print("No Missing Values Found!")
        
    
    ## Finding Duplicate Rows of Each Datasets

    print("Duplicate Rows:",df.duplicated().sum())                          ## Finding Duplicates records 
    print("\n")
    
    ## Sample Data
    
    print("\n First 5 Rows:")
    display(df.head())                                                      ## Give First 5 rows of Each datasets
    
    print("\n Last 5 Rows:")
    display(df.tail())                                                      ## Give Last 5 rows of Each Datasets.

## Numerical Summary

    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if num_cols:
        print("\n📊 Numerical Columns Summary:")
        display(df[num_cols].describe().T)
        
## Categorical Columns - unique counts

    cat_cols = df.select_dtypes(include = ['str','category']).columns.tolist()
    if cat_cols:
        print("\n Categorical Columns - Unique Value Counts:")
        unique_counts = pd.DataFrame({
            "Column": cat_cols,
            "Unique Values": [df[col].nunique() for col in cat_cols],
            "Most Frequent": [df[col].mode()[0] if not df[col].mode().empty else None for col in cat_cols]
        })
        display(unique_counts.sort_values("Unique Values",ascending= False))
        
## Run Profiling on All Datasets

for name, df in datasets.items():
    profiling_dataframe(name, df)

================================================================================
Dataset:CUSTOMERS
================================================================================
Shape: 25000 rows * 17 columns

Column Name and Data Types:

                      Column Data types  Non-Null Count  Null Count  Null %
0                customer_id        str           25000           0    0.00
1       customer_signup_date        str           25000           0    0.00
2                     gender        str           25000           0    0.00
3                        age    float64           24750         250    1.00
4                  age_group        str           25000           0    0.00
5                      state        str           25000           0    0.00
6                       city        str           25000           0    0.00
7             pincode_prefix      int64           25000           0    0.00
8           customer_segment        str           25000           0    0.00
9           preferred_device        str           24875         125    0.50
10  preferred_payment_method        str           25000           0    0.00
11              total_orders      int64           25000           0    0.00
12               total_spend    float64           25000           0    0.00
13           last_order_date        str           22700        2300    9.20
14       average_order_value    float64           25000           0    0.00
15           customer_status        str           25000           0    0.00
16              loyalty_tier        str           25000           0    0.00

Missing value:
Columns with Missing Values:

                  Missing count  Missing %
last_order_date            2300       9.20
age                         250       1.00
preferred_device            125       0.50

Duplicate Rows: 0



 First 5 Rows:

,customer_id,customer_signup_date,gender,age,age_group,state,city,pincode_prefix,customer_segment,preferred_device,preferred_payment_method,total_orders,total_spend,last_order_date,average_order_value,customer_status,loyalty_tier
0,CUST100000,09-01-2023,Male,44.00,35-44,Madhya Pradesh,Indore,607,Regular,Mobile App,EMI,3,36884.57,26-05-2023,12294.86,Churned,Bronze
1,CUST100001,10-04-2023,Male,20.00,18-24,West Bengal,Kolkata,245,Regular,Mobile App,Cash on Delivery,7,371585.73,23-05-2024,53083.68,Churned,Gold
2,CUST100002,09-05-2025,Female,35.00,35-44,Gujarat,Ahmedabad,160,Premium,Mobile Web,UPI,10,114901.74,14-07-2025,11490.17,At Risk,Silver
3,CUST100003,24-12-2024,Female,34.00,25-34,Maharashtra,Pune,175,New,Mobile App,UPI,1,3788.82,19-12-2025,3788.82,Active,Bronze
4,CUST100004,15-08-2023,Male,38.00,35-44,Andhra Pradesh,Visakhapatnam,446,Budget,Desktop,Cash on Delivery,2,61295.90,01-11-2023,30647.95,Churned,Silver

 Last 5 Rows:

,customer_id,customer_signup_date,gender,age,age_group,state,city,pincode_prefix,customer_segment,preferred_device,preferred_payment_method,total_orders,total_spend,last_order_date,average_order_value,customer_status,loyalty_tier
24995,CUST124995,02-03-2024,Male,33.00,25-34,Tamil Nadu,Coimbatore,740,New,Mobile App,UPI,0,0.00,NaN,0.00,Never Purchased,Bronze
24996,CUST124996,19-06-2023,Female,52.00,45-54,Haryana,Faridabad,762,Premium,Mobile App,Cash on Delivery,12,248614.37,23-06-2024,20717.86,Churned,Gold
24997,CUST124997,01-11-2025,Male,18.00,18-24,Punjab,Ludhiana,668,Regular,Mobile App,UPI,4,197907.83,12-12-2025,49476.96,Active,Gold
24998,CUST124998,01-02-2025,Male,35.00,35-44,Uttar Pradesh,Kanpur,636,New,Mobile App,Cash on Delivery,0,0.00,NaN,0.00,Never Purchased,Bronze
24999,CUST124999,23-11-2025,Female,51.00,45-54,West Bengal,Kolkata,348,Budget,Mobile Web,UPI,2,10526.56,19-12-2025,5263.28,Active,Bronze

📊 Numerical Columns Summary:

,count,mean,std,min,25%,50%,75%,max
age,24750.00,31.82,8.52,18.00,25.00,32.00,38.00,67.00
pincode_prefix,25000.00,499.50,231.23,100.00,298.00,501.00,700.00,899.00
total_orders,25000.00,3.88,3.32,0.00,1.00,3.00,5.00,24.00
total_spend,25000.00,100031.11,130582.71,0.00,11598.90,47466.04,140534.11,1310772.39
average_order_value,25000.00,22135.36,26901.86,0.00,5633.31,14197.18,29427.04,381793.12

 Categorical Columns - Unique Value Counts:

                      Column  Unique Values Most Frequent
0                customer_id          25000    CUST100000
1       customer_signup_date           1096    28-02-2023
9            last_order_date           1074    31-12-2025
5                       city             31          Pune
4                      state             15   Maharashtra
8   preferred_payment_method             10           UPI
3                  age_group              5         25-34
10           customer_status              4       Churned
11              loyalty_tier              4        Bronze
6           customer_segment              4       Regular
2                     gender              3          Male
7           preferred_device              3    Mobile App

================================================================================
Dataset:CUSTOMER_REVIEWS
================================================================================
Shape: 77530 rows * 8 columns

Column Name and Data Types:

              Column Data types  Non-Null Count  Null Count  Null %
0          review_id        str           77530           0    0.00
1           order_id        str           77530           0    0.00
2        customer_id        str           77530           0    0.00
3         product_id        str           77530           0    0.00
4        review_date        str           77530           0    0.00
5             rating      int64           77530           0    0.00
6   review_sentiment        str           77297         233    0.30
7  verified_purchase       bool           77530           0    0.00

Missing value:
Columns with Missing Values:

                  Missing count  Missing %
review_sentiment            233       0.30

Duplicate Rows: 0



 First 5 Rows:

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
0,REV100000,ORD1000002,CUST120793,PROD10470,2024-12-30,4,Positive,True
1,REV100001,ORD1000005,CUST123408,PROD10085,2025-02-04,4,Positive,True
2,REV100002,ORD1000005,CUST123408,PROD10233,2025-01-27,5,Positive,True
3,REV100003,ORD1000006,CUST117355,PROD10176,2025-06-11,4,Positive,True
4,REV100004,ORD1000006,CUST117355,PROD10210,2025-06-06,3,Neutral,True

 Last 5 Rows:

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
77525,REV177525,ORD1099994,CUST115127,PROD10380,2025-04-18,3,Neutral,True
77526,REV177526,ORD1099996,CUST107829,PROD10203,2024-09-22,4,Positive,True
77527,REV177527,ORD1099998,CUST109794,PROD10024,2024-11-19,5,Positive,True
77528,REV177528,ORD1099999,CUST118669,PROD10484,2025-12-31,3,Neutral,True
77529,REV177529,ORD1099999,CUST118669,PROD10246,2025-12-31,2,Negative,True

📊 Numerical Columns Summary:

          count  mean  std  min  25%  50%  75%  max
rating 77530.00  3.69 0.90 1.00 3.00 4.00 4.00 5.00

 Categorical Columns - Unique Value Counts:

             Column  Unique Values Most Frequent
0         review_id          77530     REV100000
1          order_id          54363    ORD1001080
2       customer_id          19242    CUST123291
4       review_date           1087    2025-12-31
3        product_id            550     PROD10403
5  review_sentiment              3      Positive

================================================================================
Dataset:ORDERS
================================================================================
Shape: 100000 rows * 14 columns

Column Name and Data Types:

                 Column Data types  Non-Null Count  Null Count  Null %
0              order_id        str          100000           0    0.00
1           customer_id        str          100000           0    0.00
2            order_date        str          100000           0    0.00
3            order_time        str          100000           0    0.00
4          order_status        str          100000           0    0.00
5       shipping_method        str          100000           0    0.00
6         delivery_city        str          100000           0    0.00
7        delivery_state        str          100000           0    0.00
8           coupon_code        str           66289       33711   33.71
9   discount_percentage      int64          100000           0    0.00
10             subtotal    float64          100000           0    0.00
11         shipping_fee      int64          100000           0    0.00
12           tax_amount    float64          100000           0    0.00
13         final_amount    float64          100000           0    0.00

Missing value:
Columns with Missing Values:

             Missing count  Missing %
coupon_code          33711      33.71

Duplicate Rows: 0



 First 5 Rows:

,order_id,customer_id,order_date,order_time,order_status,shipping_method,delivery_city,delivery_state,coupon_code,discount_percentage,subtotal,shipping_fee,tax_amount,final_amount
0,ORD1000000,CUST103868,16-08-2025,22:35:23,Failed,Next-Day,Mumbai,Maharashtra,FEST20,5,14439.90,0,722.00,15161.90
1,ORD1000001,CUST118472,11-02-2023,18:51:17,Delivered,Economy/Surface,Thiruvananthapuram,Kerala,FEST20,15,4760.00,0,238.00,4998.00
2,ORD1000002,CUST120793,14-12-2024,11:08:38,Delivered,Economy/Surface,Nagpur,Maharashtra,APP5,30,826.00,0,41.30,867.30
3,ORD1000003,CUST109166,23-11-2025,09:32:24,Failed,Express,Kochi,Kerala,BIGBILLION,5,25878.00,0,1293.90,27171.90
4,ORD1000004,CUST119895,27-07-2025,20:35:25,Cancelled,Standard,Jaipur,Rajasthan,SAVE15,30,3450.00,0,172.50,3622.50

 Last 5 Rows:

,order_id,customer_id,order_date,order_time,order_status,shipping_method,delivery_city,delivery_state,coupon_code,discount_percentage,subtotal,shipping_fee,tax_amount,final_amount
99995,ORD1099995,CUST120257,28-12-2025,20:16:02,Processing,Next-Day,Nagpur,Maharashtra,FLAT50,10,12142.35,0,607.12,12749.47
99996,ORD1099996,CUST107829,02-09-2024,14:27:56,Delivered,Economy/Surface,Vadodara,Gujarat,FEST20,15,21615.00,0,1080.75,22695.75
99997,ORD1099997,CUST108115,22-04-2024,20:44:15,Delivered,Next-Day,Vadodara,Gujarat,FREESHIP,25,3957.60,0,197.88,4155.48
99998,ORD1099998,CUST109794,27-10-2024,22:37:35,Delivered,Standard,Vadodara,Gujarat,NaN,20,10518.70,0,525.94,11044.64
99999,ORD1099999,CUST118669,15-12-2025,15:38:19,Delivered,Standard,Pune,Maharashtra,FEST20,15,226997.00,0,11349.85,238346.85

📊 Numerical Columns Summary:

,count,mean,std,min,25%,50%,75%,max
discount_percentage,100000.00,11.98,10.69,0.00,0.00,10.00,20.00,30.00
subtotal,100000.00,24498.99,42814.40,33.50,3449.64,9050.77,24531.30,578151.00
shipping_fee,100000.00,1.98,12.41,0.00,0.00,0.00,0.00,149.00
tax_amount,100000.00,1224.95,2140.72,1.68,172.48,452.53,1226.56,28907.55
final_amount,100000.00,25725.92,44954.00,71.00,3622.12,9503.31,25757.86,607058.55

 Categorical Columns - Unique Value Counts:

            Column  Unique Values Most Frequent
0         order_id         100000    ORD1000000
3       order_time          51489      19:07:28
1      customer_id          22820    CUST107174
2       order_date           1096    31-12-2025
6    delivery_city             31        Mumbai
7   delivery_state             15   Maharashtra
8      coupon_code              8     WELCOME10
4     order_status              5     Delivered
5  shipping_method              5      Standard

================================================================================
Dataset:ORDER_ITEMS
================================================================================
Shape: 254331 rows * 9 columns

Column Name and Data Types:

                Column Data types  Non-Null Count  Null Count  Null %
0        order_item_id        str          254331           0    0.00
1             order_id        str          254331           0    0.00
2           product_id        str          254331           0    0.00
3             quantity      int64          254331           0    0.00
4           unit_price    float64          254331           0    0.00
5  discount_percentage    float64          254331           0    0.00
6         item_revenue    float64          254331           0    0.00
7            item_cost    float64          254331           0    0.00
8               profit    float64          254331           0    0.00

Missing value:
No Missing Values Found!
Duplicate Rows: 0



 First 5 Rows:

,order_item_id,order_id,product_id,quantity,unit_price,discount_percentage,item_revenue,item_cost,profit
0,OI10000000,ORD1000000,PROD10347,4,150.00,6.50,561.00,515.92,45.08
1,OI10000001,ORD1000000,PROD10510,1,1150.00,5.00,1092.50,752.18,340.32
2,OI10000002,ORD1000000,PROD10305,2,960.00,8.00,1766.40,1217.66,548.74
3,OI10000003,ORD1000000,PROD10092,4,920.00,5.00,3496.00,3049.52,446.48
4,OI10000004,ORD1000000,PROD10417,3,2640.00,5.00,7524.00,6847.65,676.35

 Last 5 Rows:

,order_item_id,order_id,product_id,quantity,unit_price,discount_percentage,item_revenue,item_cost,profit
254326,OI10254326,ORD1099998,PROD10510,1,1150.00,20.00,920.00,752.18,167.82
254327,OI10254327,ORD1099998,PROD10365,3,360.00,20.00,864.00,731.79,132.21
254328,OI10254328,ORD1099998,PROD10392,1,8430.00,21.50,6617.55,5840.02,777.53
254329,OI10254329,ORD1099999,PROD10484,3,4060.00,15.00,10353.00,10325.49,27.51
254330,OI10254330,ORD1099999,PROD10246,4,66050.00,18.00,216644.00,226671.32,-10027.32

📊 Numerical Columns Summary:

,count,mean,std,min,25%,50%,75%,max
quantity,254331.00,2.30,1.14,1.00,1.00,2.00,3.00,8.00
unit_price,254331.00,4796.39,11229.24,50.00,570.00,1210.00,3150.00,76020.00
discount_percentage,254331.00,12.90,10.74,0.00,3.00,11.50,21.50,33.00
item_revenue,254331.00,9632.72,25845.81,33.50,884.00,2245.80,6289.50,577752.00
item_cost,254331.00,8856.98,25305.47,34.12,713.76,1772.40,5141.92,551799.68
profit,254331.00,775.74,3639.70,-108249.36,63.06,315.29,982.41,75057.36

 Categorical Columns - Unique Value Counts:

          Column  Unique Values Most Frequent
0  order_item_id         254331    OI10000000
1       order_id         100000    ORD1000000
2     product_id            550     PROD10403

================================================================================
Dataset:PRODUCTS
================================================================================
Shape: 550 rows * 14 columns

Column Name and Data Types:

                  Column Data types  Non-Null Count  Null Count  Null %
0             product_id        str             550           0    0.00
1           product_name        str             550           0    0.00
2               category        str             550           0    0.00
3            subcategory        str             550           0    0.00
4                  brand        str             550           0    0.00
5                  price    float64             550           0    0.00
6             cost_price    float64             550           0    0.00
7         discount_range        str             550           0    0.00
8         rating_average    float64             546           4    0.73
9           rating_count      int64             550           0    0.00
10        stock_quantity      int64             550           0    0.00
11   product_launch_date        str             550           0    0.00
12          product_type        str             550           0    0.00
13  return_rate_baseline    float64             550           0    0.00

Missing value:
Columns with Missing Values:

                Missing count  Missing %
rating_average              4       0.73

Duplicate Rows: 0



 First 5 Rows:

,product_id,product_name,category,subcategory,brand,price,cost_price,discount_range,rating_average,rating_count,stock_quantity,product_launch_date,product_type,return_rate_baseline
0,PROD10000,Sen Basic Staple,Grocery,Staples,Sen,220.00,173.88,0-15%,4.40,32,1422,2025-12-12,Premium,0.01
1,PROD10001,Gupta-Chandra Essential Men's Bottomwear,Fashion,Men's Bottomwear,Gupta-Chandra,4060.00,2375.50,10-25%,5.00,13,1595,2023-09-01,Budget,0.17
2,PROD10002,"Murty, Advanced Women's Casual",Footwear,Women's Casual,"Murty,",2800.00,1740.98,25-40%,4.20,139,732,2024-12-24,Premium,0.22
3,PROD10003,Madan-Kanda Signature Bedding,Home & Kitchen,Bedding,Madan-Kanda,5680.00,4330.67,15-30%,4.10,31,1181,2024-03-28,Premium,0.07
4,PROD10004,"Sami, Premium Home Decor",Home & Kitchen,Home Decor,"Sami,",370.00,250.98,25-40%,4.50,279,2597,2024-02-03,Standard,0.07

 Last 5 Rows:

,product_id,product_name,category,subcategory,brand,price,cost_price,discount_range,rating_average,rating_count,stock_quantity,product_launch_date,product_type,return_rate_baseline
545,PROD10545,Ray Classic Phone Case,Mobile Accessories,Phone Cases,Ray,500.00,333.08,30-45%,4.70,11,1095,2024-08-08,Standard,0.07
546,PROD10546,Wali-Nadig Compact Staple,Grocery,Staples,Wali-Nadig,470.00,380.52,5-20%,4.70,22,2230,2023-10-26,Budget,0.01
547,PROD10547,Mody-Kari Signature Ayurveda,Health & Wellness,Ayurveda,Mody-Kari,1210.00,887.73,20-35%,3.90,26,28,2025-01-06,Standard,0.03
548,PROD10548,Chanda Everyday Kids Wear,Fashion,Kids Wear,Chanda,700.00,431.96,20-35%,4.50,163,2985,2025-07-09,Standard,0.22
549,PROD10549,"Sunder, Smart Medical Device",Health & Wellness,Medical Devices,"Sunder,",860.00,625.00,25-40%,4.00,125,231,2023-12-16,Standard,0.04

📊 Numerical Columns Summary:

,count,mean,std,min,25%,50%,75%,max
price,550.00,4429.64,10207.04,50.00,450.00,1075.00,2962.50,76020.00
cost_price,550.00,3531.20,8786.80,34.12,307.36,717.18,2076.40,68974.96
rating_average,546.00,4.01,0.43,2.80,3.70,4.00,4.30,5.00
rating_count,550.00,126.94,237.04,0.00,22.00,54.00,131.75,2161.00
stock_quantity,550.00,1487.60,859.79,11.00,759.50,1521.00,2215.25,2994.00
return_rate_baseline,550.00,0.08,0.05,0.01,0.03,0.07,0.10,0.27

 Categorical Columns - Unique Value Counts:

                Column  Unique Values            Most Frequent
0           product_id            550                PROD10000
1         product_name            549  Morar Basic Art Supplie
6  product_launch_date            439               2025-02-24
4                brand            148                    Handa
3          subcategory             90               Home Decor
2             category             22                  Fashion
5       discount_range              7                   20-35%
7         product_type              4                 Standard

================================================================================
Dataset:PAYMENTS
================================================================================
Shape: 100000 rows * 8 columns

Column Name and Data Types:

            Column Data types  Non-Null Count  Null Count  Null %
0       payment_id        str          100000           0    0.00
1         order_id        str          100000           0    0.00
2     payment_date        str          100000           0    0.00
3   payment_method        str          100000           0    0.00
4   payment_status        str          100000           0    0.00
5      amount_paid    float64          100000           0    0.00
6  transaction_fee    float64          100000           0    0.00
7    refund_amount    float64          100000           0    0.00

Missing value:
No Missing Values Found!
Duplicate Rows: 0



 First 5 Rows:

,payment_id,order_id,payment_date,payment_method,payment_status,amount_paid,transaction_fee,refund_amount
0,PAY1000000,ORD1000000,2025-08-16,EMI,Failed,0.00,0.00,0.00
1,PAY1000001,ORD1000001,2023-02-12,UPI,Success,4998.00,0.00,0.00
2,PAY1000002,ORD1000002,2024-12-14,Net Banking,Success,867.30,0.00,0.00
3,PAY1000003,ORD1000003,2025-11-23,Cash on Delivery,Not Charged,0.00,0.00,0.00
4,PAY1000004,ORD1000004,2025-07-27,Cash on Delivery,Not Charged,0.00,0.00,0.00

 Last 5 Rows:

,payment_id,order_id,payment_date,payment_method,payment_status,amount_paid,transaction_fee,refund_amount
99995,PAY1099995,ORD1099995,2025-12-29,Net Banking,Success,12749.47,0.00,0.00
99996,PAY1099996,ORD1099996,2024-09-02,Cash on Delivery,Success,22695.75,0.00,0.00
99997,PAY1099997,ORD1099997,2024-04-23,Debit Card,Success,4155.48,0.00,0.00
99998,PAY1099998,ORD1099998,2024-10-27,UPI,Success,11044.64,0.00,0.00
99999,PAY1099999,ORD1099999,2025-12-15,Credit Card,Success,238346.85,3575.20,0.00

📊 Numerical Columns Summary:

,count,mean,std,min,25%,50%,75%,max
amount_paid,100000.00,23910.50,43921.74,0.00,2714.94,8278.78,23473.80,607058.55
transaction_fee,100000.00,79.65,331.41,0.00,0.00,0.00,2.45,7936.84
refund_amount,100000.00,2687.41,16340.82,0.00,0.00,0.00,0.00,541686.50

 Categorical Columns - Unique Value Counts:

           Column  Unique Values Most Frequent
0      payment_id         100000    PAY1000000
1        order_id         100000    ORD1000000
2    payment_date           1095    2025-12-31
3  payment_method             10           UPI
4  payment_status              5       Success

================================================================================
Dataset:RETURNS
================================================================================
Shape: 12075 rows * 8 columns

Column Name and Data Types:

          Column Data types  Non-Null Count  Null Count  Null %
0      return_id        str           12075           0    0.00
1       order_id        str           12075           0    0.00
2    customer_id        str           12075           0    0.00
3     product_id        str           12075           0    0.00
4    return_date        str           12075           0    0.00
5  return_reason        str           12075           0    0.00
6  refund_amount    float64           12075           0    0.00
7  return_status        str           12075           0    0.00

Missing value:
No Missing Values Found!
Duplicate Rows: 0



 First 5 Rows:

,return_id,order_id,customer_id,product_id,return_date,return_reason,refund_amount,return_status
0,RET100000,ORD1000009,CUST117396,PROD10073,2024-05-28,Changed mind,2094.40,Refund Completed
1,RET100001,ORD1000019,CUST122124,PROD10077,2023-12-30,Product damaged,1040.00,Refund Completed
2,RET100002,ORD1000019,CUST122124,PROD10451,2024-01-06,Wrong product,0.00,Pending
3,RET100003,ORD1000019,CUST122124,PROD10043,2024-01-05,Quality issue,15104.00,Refund Completed
4,RET100004,ORD1000028,CUST101962,PROD10171,2023-06-19,Changed mind,0.00,Pending

 Last 5 Rows:

,return_id,order_id,customer_id,product_id,return_date,return_reason,refund_amount,return_status
12070,RET112070,ORD1099916,CUST114201,PROD10328,2025-12-17,Late delivery,31338.75,Refund Completed
12071,RET112071,ORD1099948,CUST113856,PROD10376,2023-05-25,Size issue,16636.65,Refund Completed
12072,RET112072,ORD1099971,CUST108197,PROD10205,2023-08-21,Product not as expected,0.00,Pending
12073,RET112073,ORD1099975,CUST123174,PROD10035,2025-10-23,Product damaged,4396.00,Refund Completed
12074,RET112074,ORD1099980,CUST123614,PROD10482,2024-12-28,Product not as expected,140.00,Refund Completed

📊 Numerical Columns Summary:

                 count    mean      std  min    25%     50%     75%       max
refund_amount 12075.00 8770.05 24672.23 0.00 552.00 1960.15 5880.00 384411.00

 Categorical Columns - Unique Value Counts:

          Column  Unique Values     Most Frequent
0      return_id          12075         RET100000
1       order_id           9510        ORD1002445
2    customer_id           7285        CUST118109
4    return_date           1078        2025-12-31
3     product_id            523         PROD10403
5  return_reason              8        Size issue
6  return_status              4  Refund Completed

================================================================================
Dataset:SHIPMENTS
================================================================================
Shape: 89681 rows * 11 columns

Column Name and Data Types:

                    Column Data types  Non-Null Count  Null Count  Null %
0              shipment_id        str           89681           0    0.00
1                 order_id        str           89681           0    0.00
2           warehouse_city        str           89681           0    0.00
3            delivery_city        str           89681           0    0.00
4          shipping_method        str           89681           0    0.00
5            dispatch_date        str           89681           0    0.00
6   expected_delivery_date        str           89681           0    0.00
7     actual_delivery_date        str           87360        2321    2.59
8            delivery_days    float64           87360        2321    2.59
9          delivery_status        str           89681           0    0.00
10            delayed_flag      int64           89681           0    0.00

Missing value:
Columns with Missing Values:

                      Missing count  Missing %
actual_delivery_date           2321       2.59
delivery_days                  2321       2.59

Duplicate Rows: 0



 First 5 Rows:

,shipment_id,order_id,warehouse_city,delivery_city,shipping_method,dispatch_date,expected_delivery_date,actual_delivery_date,delivery_days,delivery_status,delayed_flag
0,SHIP1000000,ORD1000001,Chennai,Thiruvananthapuram,Economy/Surface,2023-02-11,2023-02-19,2023-02-17,6.00,Delivered,0
1,SHIP1000001,ORD1000002,Mumbai,Nagpur,Economy/Surface,2024-12-15,2024-12-23,2024-12-26,11.00,Delivered,1
2,SHIP1000002,ORD1000005,Chennai,Coimbatore,Standard,2025-01-09,2025-01-13,2025-01-12,3.00,Delivered,0
3,SHIP1000003,ORD1000006,Delhi-NCR (Gurugram),Noida,Same-Day,2025-05-26,2025-05-26,2025-05-27,1.00,Delivered,1
4,SHIP1000004,ORD1000007,Chennai,Thiruvananthapuram,Express,2025-10-04,2025-10-06,NaN,NaN,Cancelled in Transit,0

 Last 5 Rows:

,shipment_id,order_id,warehouse_city,delivery_city,shipping_method,dispatch_date,expected_delivery_date,actual_delivery_date,delivery_days,delivery_status,delayed_flag
89676,SHIP1089676,ORD1099994,Kolkata,Patna,Economy/Surface,2025-03-26,2025-04-03,2025-04-05,10.00,Delivered,1
89677,SHIP1089677,ORD1099996,Ahmedabad,Vadodara,Economy/Surface,2024-09-03,2024-09-11,2024-09-16,13.00,Delivered,1
89678,SHIP1089678,ORD1099997,Ahmedabad,Vadodara,Next-Day,2024-04-23,2024-04-25,2024-04-29,6.00,Delivered,1
89679,SHIP1089679,ORD1099998,Ahmedabad,Vadodara,Standard,2024-10-27,2024-10-31,2024-10-30,3.00,Delivered,0
89680,SHIP1089680,ORD1099999,Mumbai,Pune,Standard,2025-12-15,2025-12-19,2025-12-21,6.00,Delivered,1

📊 Numerical Columns Summary:

                 count  mean  std  min  25%  50%  75%   max
delivery_days 87360.00  4.10 2.51 0.00 2.00 4.00 6.00 14.00
delayed_flag  89681.00  0.42 0.49 0.00 0.00 0.00 1.00  1.00

 Categorical Columns - Unique Value Counts:

                   Column  Unique Values         Most Frequent
0             shipment_id          89681           SHIP1000000
1                order_id          89681            ORD1000001
5           dispatch_date           1095            2025-12-25
6  expected_delivery_date           1091            2025-12-31
7    actual_delivery_date           1091            2025-12-31
3           delivery_city             31                  Pune
2          warehouse_city              7  Delhi-NCR (Gurugram)
4         shipping_method              5              Standard
8         delivery_status              3             Delivered

 #### 4. Aditional Important Checks

In [16]:
## Aditional Imported Checks like primary key, Date range, value count

print("="*80)
print("Additional Important Checks")
print("="*80)

# ----------- Check Primary Key candidates ---------

print("\n Checking Potential Primary Keys (Uniqueness):\n")

key_checks = {
    "customers" : "customer_id",
    "products" : "product_id",
    "orders" : "order_id",
    "order_items": "order_item_id",
    "payments": "payment_id",
    "shipments": "shipment_id",
    "returns": "return_id",
    "customer_reviews": "review_id"
}

for table , key_col in key_checks.items():
    if table in datasets and key_col in datasets[table].columns:
        total = len(datasets[table])
        unique = datasets[table][key_col].nunique()
        is_unique = total == unique
        status = "Unique (Primary key)" if is_unique else " Not Unique"
        print(f"{table:15} - {key_col:20} | Total : {total:,} | Unique : {unique:,} | {status}")
    else:
        print(f"{table:15} - Column '{key_col}' not found (please check actual column name)")
        

# ----------- Date Range Check (Orders) ---------

print("\n Data Range Analysis:")

if "orders" in datasets:
    orders = datasets['orders']
    
    # Trying Comman date column
    date_cols = [col for col in orders.columns if 'date' in col.lower() or 'time' in col.lower()]
    print(f"possible date columns in orders: {date_cols}")
    
    for col in date_cols:
        try:
            orders[col] = pd.to_datetime(orders[col], dayfirst=True, errors='coerce')
            print(f"\n{col}")
            print(f"Min Date : {orders[col].min()}")
            print(f"Max Date : {orders[col].max()}")
            print(f"Null     : {orders[col].isnull().sum()}")
        except:
            print(f"Could not convert {col} to datetime")

================================================================================
Additional Important Checks
================================================================================

 Checking Potential Primary Keys (Uniqueness):

customers       - customer_id          | Total : 25,000 | Unique : 25,000 | Unique (Primary key)
products        - product_id           | Total : 550 | Unique : 550 | Unique (Primary key)
orders          - order_id             | Total : 100,000 | Unique : 100,000 | Unique (Primary key)
order_items     - order_item_id        | Total : 254,331 | Unique : 254,331 | Unique (Primary key)
payments        - payment_id           | Total : 100,000 | Unique : 100,000 | Unique (Primary key)
shipments       - shipment_id          | Total : 89,681 | Unique : 89,681 | Unique (Primary key)
returns         - return_id            | Total : 12,075 | Unique : 12,075 | Unique (Primary key)
customer_reviews - review_id            | Total : 77,530 | Unique : 77,530 | Unique (Primary key)

 Data Range Analysis:
possible date columns in orders: ['order_date', 'order_time']

order_date
Min Date : 2023-01-01 00:00:00
Max Date : 2025-12-31 00:00:00
Null     : 0

order_time
Min Date : 2026-10-23 00:00:02
Max Date : 2026-10-23 23:59:59
Null     : 0

### Summary

In this notebook, we performed Initial Data Profiling on all the raw datasets used in the Indian E-Commerce Sales & Customer Analytics project.

**Key activities completed:**

- Loaded all required CSV files (customers, products, orders, order_items, payments, shipments, returns, and reviews).
- Checked the shape (rows × columns) of each dataset.
- Examined data types of all columns.
- Identified missing values and their percentage.
- Checked for duplicate records.
- Reviewed sample records (first 5 rows).
- Analyzed numerical and categorical columns.
- Verified uniqueness of potential Primary Key columns.
- Checked date ranges in the orders data.